-- System.Standard_Library body for Z80
-- Interface to standard library initialization

package body System.Standard_Library is

   -- Last exception data
   Last_Exception : System.Address := System.Null_Address;

   ---------------------------
   -- Exception_Information --
   ---------------------------

   function Exception_Information return System.Address is
   begin
      return Last_Exception;
   end Exception_Information;

   -------------
   -- Adainit --
   -------------

   procedure Adainit is
   begin
      -- Initialize elaboration flags and call elaboration code
      -- Actual implementation generated by binder
      null;
   end Adainit;

   --------------
   -- Adafinal --
   --------------

   procedure Adafinal is
   begin
      -- Finalize controlled objects
      -- Actual implementation generated by binder
      null;
   end Adafinal;

   -----------------
   -- Exit_Status --
   -----------------

   procedure Exit_Status (Status : Integer) is
      pragma Unreferenced (Status);
   begin
      -- CP/M exit - warm boot
      -- Actual assembly: JP 0000h
      null;
   end Exit_Status;

end System.Standard_Library;
